pipeline {
    agent any

    environment {
        GRADLE_OPTS = '-Dorg.gradle.daemon=false'
        DB_USERNAME = 'user_products'
        DB_PORT = '5433'
        DB_NAME = 'products'
        DB_HOST = 'localhost'
        DB_PASSWORD = 'Cl4v3_S3cret4'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Grant execute permission for gradlew') {
            steps {
                dir('ms_products') {
                    sh 'chmod +x gradlew'
                }
            }
        }

        stage('Runing Test And Generate Coverage Report') {
            steps {
                dir('ms_products') {
                    sh '''
                        export DB_USERNAME=${DB_USERNAME}
                        export DB_PORT=${DB_PORT}
                        export DB_NAME=${DB_NAME}
                        export DB_HOST=${DB_HOST}
                        export DB_PASSWORD=${DB_PASSWORD}
                        ./gradlew jacocoTestReport
                    '''
                }
            }
        }

        stage('Check Coverage') {
            steps {
                script {
                    def coverageFile = readFile('ms_products/build/reports/jacoco/test/jacocoTestReport.xml')
                    def coverage = new XmlSlurper().parseText(coverageFile)
                    def lineCoverage = coverage.counter.find { it.@type == 'LINE' }
                    def covered = lineCoverage.@covered.toInteger()
                    def missed = lineCoverage.@missed.toInteger()
                    def total = covered + missed
                    def coveragePercentage = (covered / total) * 100

                    echo "Line Coverage: ${coveragePercentage}%"

                    if (coveragePercentage < 80) {
                        error "Coverage is below 80%: ${coveragePercentage}%"
                    }
                }
            }
        }

        stage('Publish Coverage Report') {
            steps {
                jacoco execPattern: 'ms_products/build/jacoco/test.exec', classPattern: 'ms_products/build/classes/java/main', sourcePattern: 'ms_products/src/main/java', exclusionPattern: '**/Test*'
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: 'ms_products/build/reports/**', allowEmptyArchive: true
            junit 'ms_products/build/test-results/test/*.xml'
            cleanWs()
        }
        failure {
            cleanWs()
        }
    }
}