name: CI Pipeline

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: 'adopt'
                  java-version: '17'

            - name: Cache Gradle packages
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-

            - name: Grant execute permission for gradlew
              run: chmod +x ms_products/gradlew

            - name: Run unit tests
              env:
                GRADLE_OPTS: '-Dorg.gradle.daemon=false'
                DB_USERNAME: ${{ secrets.DB_USERNAME }}
                DB_PORT: ${{ secrets.DB_PORT }}
                DB_NAME: ${{ secrets.DB_NAME }}
                DB_HOST: ${{ secrets.DB_HOST }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
              run: cd ms_products && ./gradlew jacocoTestReport

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
                fail_ci_if_error: true # optional (default = false)
                files: ./ms_products/build/reports/jacoco/test/jacocoTestReport.xml 
                flags: unittests # optional
                name: jacoco-report # optional
                verbose: true # optional (default = false)
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

            - name: Upload coverage report
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-report
                  path: ms_products/build/reports/jacoco/test/html

            - name: Publish test results
              uses: actions/upload-artifact@v4
              with:
                  name: test-results
                  path: ms_products/build/test-results/test
